# docker-compose.yml
version: "3.8"

services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: librarydb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  flyway:
    image: flyway/flyway:10.15.0
    depends_on:
      - db
    command: >
      -url=jdbc:mariadb://db:3306/librarydb
      -user=root
      -password=password
      -locations=filesystem:/flyway/sql
      info
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/librarydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  db-data: