version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: librarydb
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: flyway
      MYSQL_PASSWORD: flywaypassword
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  flyway:
    image: flyway/flyway:10.15.0
    depends_on:
      - db
    command: >
      -url=jdbc:mysql://db:3306/librarydb
      -user=root
      -password=password
      -locations=filesystem:/flyway/sql
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/librarydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  db-data: